---

- name: 'INSTALL | YUM | Install system dependencies'
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ clamav_system_dependencies }}"


- name: 'INSTALL | YUM | Install packages'
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  notify:
    - 'HANDLER | Restart freshclam'
    - 'HANDLER | Update Clamv signatures'
  with_items: "{{ clamav_packages }}"
