---

# Handlers main file for clamav role

- name: 'HANDLER | Update Clamv signatures'
  become: True
  shell: >
    pidof {{ clamav_freshclam_binary | basename }}
    || {{ clamav_freshclam_binary }} -u {{ clamav_config_owner }}
    --datadir {{ clamav_clamd_database_directory }}
  tags:
    - 'role::clamav'
    - 'role::clamav::config'
    - 'role::clamav::install'


- name: 'HANDLER | Restart clamd'
  become: True
  service:
    name: "{{ clamav_clamd_service_name }}"
    sleep: "{{ clamav_clamd_service_sleep }}"
    state: 'restarted'
  when: 'clamav_do_restart_clamd'
  tags:
    - 'role::clamav'
    - 'role::clamav::config'
    - 'role::clamav::install'


- name: 'HANDLER | Restart freshclam'
  become: True
  service:
    name: "{{ clamav_freshclam_service_name }}"
    sleep: "{{ clamav_freshclam_service_sleep }}"
    state: 'restarted'
  when: 'clamav_do_restart_freshclam'
  tags:
    - 'role::clamav'
    - 'role::clamav::config'
    - 'role::clamav::install'
